---
- name: create user and group
  hosts: all
  vars_files:
  - project_vars
  become: True
  tasks: 
    - name: create nexus group
      group:
        name: nexus
        state: present
    - name: create nexus user
      user:
        name: nexus_user
        groups: nexus
        append: yes
    - name: reconnect
      meta: reset_connection
  
- name: install necessary tools
  hosts: all
  become: True
  tasks: 
    - name: install packages and update
      apt:
        update_cache: yes
        cache_valid_time: 3600
      apt:
        pkg: 
          - openjdk-17-jre-headless
          - net-tools

- name: downlaod nexus
  hosts: all
  become: true
  tasks:
    - name: install nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
    - debug: msg={{download_result}} 

    - name: unarchive it
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes

    - name: Delete the archive file
      file:
        path: "{{download_result.dest}}"
        state: absent

    - name: find nexus folder 
      find:
        paths: /opt
        pattern: "nexus-*" 
        file_type: directory
      register:   find_result
    - debug: msg={{find_result}}

    - name: check nexus folder stats
      stat: 
        path: /opt/nexus
      register: stat_result
    - debug: msg={{stat_result.stat.exists}}

    - name: find nexus folder and rename it
      shell: mv {{find_result.files[0].path}} /opt/nexus
      when: not stat_result.stat.exists

    - name: wait
      pause: seconds=25

    - name: change ownership

      file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus_user
        group: nexus
        mode: '0755'

      file:
        path: /opt/nexus
        state: directory
        owner: nexus_user
        group: nexus
        mode: '0755'
        
- name: modify run as user
  hosts: all
  become: true
  tasks:
    - name: run_as_user
      lineinfile:
        path: /opt/nexus/bin/nexus.rc
        regexp: '^#run_as_user="'
        line: run_as_user="nexus_user"
    - name: start nexus
      command: /opt/nexus/bin/nexus start
